@startuml
top to bottom direction
skinparam backgroundcolor transparent

scale 3

rectangle UI

rectangle "View (API)"
rectangle Model

UI -[#silver]-> "View (API)"
"View (API)" -[#silver]-> Model

@enduml